name: Javaapp build
on: 
  push: 
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4 # Use the latest version
    - name: Set up JDK 21        # Step 2: Install Java
      uses: actions/setup-java@v4
      with: # used for providing input
          java-version: '21'
          distribution: 'temurin'
          cache: maven             # Step 3: Enable dependency caching

    - name: Build with Maven     # Step 4: Run the build
      run: mvn -B package --file pom.xml